book/urls.py
from django.urls import re_path
from . import views

app_name = 'book'

#url for app
urlpatterns = [
    re_path(r'^$', views.form, name='form'),
    re_path(r'^delete-activity/(?P<pk>\d+)/$', views.delete_activity, name='delete_activity'),
]

homepage/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include
from listresto import urls

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name = "home"),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

info/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include

app_name = 'info'

urlpatterns = [
    path('', views.info, name = "info"),
    path('addLikes/', views.addLikes, name = "addLikes")
]

listresto/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include

app_name = 'listresto'

urlpatterns = [
    path('', views.listresto, name = "listresto"),
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('homepage.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('listresto/', include('listresto.urls')),
    path('info/', include('info.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

book/models.py
from django.db import models

# Create your models here.
class ActivityModel(models.Model):
    date = models.DateField()
    hour = models.TimeField(auto_now_add=False)
    name = models.CharField(max_length=100)

homepage/models.py
from django.db import models
from django.utils import timezone

# from django.forms import ModelForm

# Create your models here.
   
class Rest(models.Model):
    
    place   = models.CharField(max_length= 30 ,default="jabodetabek")

    def __str__(self):
        return self.place

class Restaurant(models.Model):
    places  = models.ForeignKey(Rest, on_delete=models.CASCADE)
    nama    = models.CharField(max_length = 30 , default="Random")
    alamat = models.CharField(max_length = 50, default = 'Jl. Depok Kota Depok')
    phone = models.CharField(max_length = 30, default = '0878xxxx')
    desc = models.TextField(default = '')


    likes = models.IntegerField(default = 0)
    image = models.CharField(max_length = 100, default = ".")

    def __str__(self):
        return self.nama

info/models.py
from django.db import models
from homepage.models import Restaurant

# Create your models here.
class Review(models.Model):
    namaResto = models.ForeignKey(Restaurant, on_delete = models.CASCADE)
    
    name = models.CharField(max_length = 25, default = '')
    content = models.TextField(default = '')

    def __str__(self):
        return self.name

listresto/models.py
from django.db import models

# Create your models here.

book/forms.py
from django.db import models
from django import forms
from .models import ActivityModel


import datetime

class ActivityForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs = {
            "placeholder": 'Name'
        }
    ))
    date = forms.DateField(input_formats=['%Y-%m-%d'], widget=forms.TextInput(
        attrs = {
            "placeholder": 'YYYY-MM-DD'
        }
    ))
    hour = forms.TimeField(input_formats=['%H:%M'], widget=forms.TimeInput(
        attrs = {
            "placeholder": 'Hour:Minute'
        }
    ))


    class Meta:
        model = ActivityModel
        fields = ("name", "date", "hour")
        labels ={
            "name": "Name",
            "date": "Date",
            "hour": "time"
        }

homepage/forms.py
from django import forms
from .models import Rest, Restaurant
from django.forms import ModelForm
from homepage import models

class RestForm(forms.Form):

    place   = forms.CharField(
            label       = 'tempat',
            max_length  = 50,
            required    = True,
            widget      = forms.TextInput(attrs = {'class' : 'form-control form-control-sm', 'placeholder':'gabut'})    
        )

class RestaurantForm(forms.Form):

    nama    = forms.CharField(
            label       = 'tempat',
            max_length  = 50,
            required    = True,
            widget      = forms.TextInput(attrs = {'class' : 'form-control form-control-sm', 'placeholder':'gabut'})    
        )

info/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm, Textarea
# import datetime

class ReviewForm(ModelForm):
    class Meta:
        model = Review

        fields = ["name", 'content']

        widgets = {
            'content': Textarea(attrs={'cols': 80, 'rows': 5}),
        }

book/views.py
from django.shortcuts import render
from django.shortcuts import render
from .models import ActivityModel
from .forms import ActivityForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages


# Create your views here.

def form(request):
    if request.method == "POST":
        data = ActivityForm(request.POST)
        if data.is_valid():
            data.save()
        data = ActivityModel.objects.all()

    if request.method == "GET":
        data = ActivityModel.objects.all()

    return render(request, 'form.html', {'form': ActivityForm(), 'data': data})

def delete_activity(request, pk):
    activity = get_object_or_404(ActivityModel, pk=pk)
    activity.delete()
    
    form = ActivityForm(instance=activity)

    context = {
        'form' : form,
    }
    return render (request, 'form.html', context)

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

from .models import Rest
from .forms import RestForm

# Create your views here.
def home(request):
    html    = "homepage.html"
    if request.method == 'GET':
            form = RestForm()
    elif request.method == 'POST':
            form = RestForm(request.POST)
            #print(request.POST)
            if form.is_valid():
                new_rest = Rest(
                    place= form.data['place']
                )

                new_rest.save()
                print(Rest.objects.all())
                form = RestForm()

                return redirect('rest')
            print(form.errors)
            
    rest    = Rest.objects.all()
    context = {
            'form': form,
            'Rest': rest,
    }
    return render(request, html, context)

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

info/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm
from .models import Review
from homepage.models import Restaurant
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def info(request):
    if request.method == 'GET':
        form = ReviewForm()
    elif request.method == 'POST':
        form = ReviewForm(request.POST)
        # print(request.POST)

        if form.is_valid():
            new_review = Review(
                namaResto = Restaurant.objects.get(id = int(request.GET.get('arg', ''))),
                name = form.data['name'],
                content = form.data['content'],
            )

            num = request.GET.get('arg', '')
            new_review.save()
            form = ReviewForm()

        return HttpResponseRedirect('/info/?arg=' + num)
    

    resto = Restaurant.objects.get(id = int(request.GET.get('arg', '')))
    reviews = Review.objects.filter(namaResto = resto)


    context = {
        'form': form,
        'reviews': reviews,
        'resto': resto,
    }

    return render(request, 'info.html', context)

def addLikes(request):
    resto = Restaurant.objects.get(id = int(request.GET.get('arg', '')))
    resto.likes += 1
    resto.save()
    return HttpResponse(content=resto.likes)

listresto/views.py
from django.shortcuts import render
from homepage.models import Restaurant

# Create your views here.
def listresto(request):
    restos = Restaurant.objects.all()

    context = {
        'restos': restos,
    }

    return render(request, 'listresto.html', context)

book/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Restaurant Reservation</title>
</head>
<body>
    <header style="padding: 100px; background-color: yellow;">
        <h1 style="text-align: center; font-family: Chewy, cursive;"><b>Restaurant Reservation Form</b></h1>
    </header>
        <nav id= "#nav_bar" class="navbar navbar-expand-lg navbar-light navbar-static-top">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="ml-auto navbar-nav">
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'info:info' %}"><b>Back</b></a></li>
                        
                    </ul>
                </div>
            </nav>        
        
    <div style="text-align: center; padding: 50px;">
        {% with url_name=request.resolver_match.url_name %}
        {% if url_name == 'form' %}
        {% else %}
            <h1>Are you sure you want to delete this reservation?</h1>
        {% endif %}
        {% endwith %}
    
        <form action="/book/" method="POST">
            {% csrf_token %}
            <table style="width: 100%; margin-top: 35px; margin-bottom: 35px; padding : 50px; text-align: center;">
                <tr>
                    {{ form.as_table }}
                </tr>
            </table>
            {% with url_name=request.resolver_match.url_name %}
            {% if url_name == 'delete_activity' %}
                <a href="{% url 'form' %}"><button class="btn btn-danger" type="submit">Delete</button></a>
            {% else %}
                <button class="btn-success" type="submit">Reserve</button>
            {% endif %}
        </form>
            {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            {% endwith %}
    </div>

    <div style="padding: 50px;">
        <table style="width: 100%; margin-top: 35px; margin-bottom: 35px; padding : 50px; text-align: center;">
                <tr style="text-align: center; font-family: Chewy, cursive;">
                  <th>Name</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th></th>
                </tr>
                <tr>
                {% for i in data %}
                <tr style="text-align: center;">
                    <td>{{i.name}}</td>
                    <td>{{i.date}}</td>
                    <td>{{i.hour}}</td>
                    <td><a href="/delete-activity/?pk=i.pk "> <button class="btn btn-danger"> Delete</button></a></td>
                </tr>
                {% endfor %}
              </table>
    </div>
    
</body>
</html>

homepage/templates/homepage.html
<!DOCTYPE html>

{% extends "homepagebase.html" %}
{% load static %}

<!--Disclaimer	: there's no bug in this code, there's only feature 
	@author		: Harnindyto wicaksana, 
	contact		: todi.to;-->

<html>
	{% block main %}
		<div>
			

			{% if user.is_authenticated %}
			<a htype="button" class="btn btn-link" href="{% url 'logout' %}" style="position:absolute;top:7%;right:7%;">logout</a>
			<div class="makeitmiddle">
			<!--
			<a class="btn-floating btn-lg btn-default float"><i class="fas fa-bolt"></i></a>
			-->
			
				<div class="inthemiddle d-flex justify-content-center">
					<img src="{% static 'images/PewLicious.png' %}" alt="PewLicious logo" align="middle" style="max-width:100%;">
				</div>
				
				<div class="inthemiddle">
					<form>
						<div class="form-group">
							<select class="form-control" id="exampleFormControlSelect1">
							
							  <option value="" selected disabled hidden>Choose city</option>	
							  {% for j in Rest %}
							  
							  <option>{{ j.place }}</option>
							  
							  {% endfor %}
							  
							</select>
						</div>
					</form>
					<div class="text-right mb-3">
						
						<button type="button" onclick="window.location.href={% url 'listresto:listresto' %}" class="btn btn-outline-danger" style="padding : 0 auto;">Hungry</button>
					</div>
				</div>
				
				{% else %}
				<div class="makeitmiddle">
					<!--
					<div class="d-flex justify-content-center">
						<h1>Login first</h1>
					</div>
						<div class="d-flex justify-content-center">
						<a htype="button" class="btn btn-link" href="{% url 'login' %}">login</a>
					</div>
					-->
					<meta http-equiv="refresh" content="0; URL={% url 'login' %}" />

				{% endif %}
			</div>
		</div>
		
	{% endblock %}
	
	{% block extra %}
	<script type="text/javascript">
	  $(document).ready(function() {
		$('.carousel').carousel({interval: 6666});
	  });
	</script>
	{% endblock %}
	
</html>

homepage/templates/signup.html
<!DOCTYPE html>

{% extends "homepagebase.html" %}
{% load static %}

<!--Disclaimer	: there's no bug in this code, there's only feature 
	@author		: Harnindyto wicaksana, 
	contact		: todi.to;-->

<html>
	  {%block main%}
	  <div class="makeitmiddle">
		<div class="inthemiddle">
			<h2>Login</h2>
			<h2>Sign up</h2>
			  <form method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit">Sign up</button>
			  </form>
		</div>
	  </div>
	  {%endblock%}
	
	
</html>

info/templates/info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static '/css/info.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Chewy&display=swap" rel="stylesheet">
    
    <script src="https://kit.fontawesome.com/26197ec3bf.js"></script>

    <title>Info Restoran</title>
</head>

<body>
    {% if user.is_authenticated %}
    <div id="header">
        <div class="container">
            <div class="container-btn">
                <div class="ml-auto">
                    <button type="button" class="btn btn-danger"><a href="/listresto/?arg={{resto.place.id}}">Back</a></button>
                </div>
            </div>

            <h1>{{ resto.nama }}</h1>

            <div class="big-container">
                <div class="container-restoran">
                    <div class="img-container">
                        <img src="{{ resto.image }}" alt="RESTORAN-DEPOK-01">
                    </div>
                    <a href="/book/?arg={{resto.id}}" class="btn btn-light">BOOK</a>
                </div>

                <div class="container-info">
                    <h4>Alamat: {{ resto.alamat }}</h4>
                    <h4>Telepon: {{ resto.phone }}</h4>
                    <p>{{ resto.desc }}</p>
                    <div class="likes"><button class="btn-like" data="{{ resto.id }}"><i class="far fa-thumbs-up"></i></button> {{ resto.likes }} &nbsp; Likes</div>
                </div>
            </div>
        </div>
    </div>

    <div id="review">
        <div class="form-container">
            <h2>Berikan Review</h2>
            <form id="form" action="/info/?arg={{resto.id}}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" id="submit_review">SUBMIT</button>
            </form>
        </div>

        <div class="reviews">
            <h4>Review</h4>
            {% for review in reviews %}
                <div class="review">
                    <h5> {{ review.name }} </h5>
                    <p> {{ review.content }} </p>
                </div>
            {% endfor %}
        </div>
    </div>

    {% else %}
    <div id="not-login">
        <div class="login-container">
            <h1>silakan pergi ke Halaman login terlebih dahulu</h1>
            <a href="{% url 'homepage:home' %}">login</a>
        </div>
    </div>
    {% endif %}
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
<script src="{% static 'js/info.js' %}"></script>

<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script>

<script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script><script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script>

<script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script>

</html>

listresto/templates/listresto.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/listresto.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List Restoran</title>
</head>
<body>
    <div id = "header">
        <div class = "container">
            <div class="top">
                <h1>Restoran Favorit di Sekitarmu:</h1>
                <div class="btn-back-2"></div>	
                    <div class="container-btn">
                        <button type="button" class="btn btn-danger" onclick="window.location.href='/'">Back</button>
                    </div>
                </div>
            </div>
        </div>

        {% for resto in restos %}
        <div class = "resto clearfix">
			<div class = "img-resto left-section">
				<img src="{{ resto.image }}" style="width: 300px; height: 200px;" alt="RESTORAN-DEPOK-01">
			</div>
			<div style="padding-top: 20px;">
				<h2>{{ resto.nama }}</h2>
				<div class = "content-resto">
					<h6>{{ resto.alamat }}</h6>
                    <h6>{{ resto.phone }}</h6>
                    <p>{{ resto.desc }}</p>
				</div>
				<div class="container-btn">
					<div class="ml-auto">
						<a class="btn btn-warning" href="/info/?arg={{resto.id}}">Lihat</a>
					</div>
				</div>
			</div>
        </div>
        {% endfor %}
		
		{% comment %} <div class = "resto clearfix">
			<div class = "img-resto left-section">
				<img src="{% static '/images/01.jpeg' %}" style="width: 300px; height: 200px;" alt="RESTORAN-DEPOK-01">
			</div>
			<div style="padding-top: 20px;">
				<h2>Toodz House</h2>
				<div class = "content-resto">
					<h6>Jl. Cipete Raya No. 79, Fatmawati, Jakarta</h6>
                    <h6>021-75930183</h6>
                    <p>Berlokasi di jalan Cipete Raya, Toodz House ini termasuk kafe yang cukup unik. Karena pada dasarnya ini adalah sebuah rumah yang disulap menjadi kafe. Bisa ditebak ambience yang ditawarkan akan sangat homey, dengan penggunaan sofa sebagai tempat duduk. Ada area indoor di dalam rumah untuk non-smoking dan outdoor di teras untuk smoking. Interior kafe dihiasi berbagai macam pernak-pernik yang biasanya kita temui di rumah tinggal. Penggunaan warna-warna hangat seperti coklat, hijau dan oranye menambah kesan homey. Pelayanannya pun excellent, sangat ramah dan juga tanggap ke customer. Tempatnya memang tidak begitu besar, jadi terkadang kafe ini bisa jadi sangat crowded dengan customer.</p>
				</div>
				<div class="container-btn">
					<div class="ml-auto">
						<button type="button" class="btn btn-warning" onclick="window.location.href={% url 'info:info' %}">Lihat</button>
					</div>
				</div>
			</div>
        </div>
        
        <div class = "resto clearfix">
			<div class = "img-resto left-section">
				<img src="{% static '/images/02.jpeg' %}" style="width: 300px; height: 200px;" alt="RESTORAN-DEPOK-01">
			</div>
			<div style="padding-top: 20px;">
				<h2>Baxtersmith Dining</h2>
				<div class = "content-resto">
                    <h6>Jl. Suryo No. 28, Senopati, Jakarta</h6>
                    <h6>021-70837181</h6>
                    <p>Baxter Smith sendiri buka sejak tahun 2016 lalu tepatnya di bulan Juni. Konsep dari Baxter Smith ini adalah one stop entertaiment. Disini tersedia dari mulai dining, bar, lounge. Baxter Smith sendiri mempunyai 3 lantai, untuk lantai 1 adalah tempat untuk dining. Konsep interior di lantai 1 ini adalah industrial jaman kolonial Inggris, dengan design menyerupai konsep mesin waktu. Terlihat jelas interior disini banyak unsur besi dan kayu sebagai ornamen interiornya. Sedangkan dilantai 2 disini adalah bar dan juga club, yang designnya seperti didalam kapal selam kuno. Dan untuk di lantai 3 sendiri merupakan lounge, disini tempatnya lebih terbuka, dan interiornya lebih banyak mengutamakan unsur kayu.</p>
				</div>
				<div class="container-btn">
					<div class="ml-auto">
						<button type="button" class="btn btn-warning" onclick="window.location.href={% url 'info:info' %}">Lihat</button>
					</div>
				</div>
			</div>
        </div>
        
        <div class = "resto clearfix">
			<div class = "img-resto left-section">
				<img src="{% static '/images/03.jpeg' %}" style="width: 300px; height: 200px;" alt="RESTORAN-DEPOK-01">
			</div>
			<div style="padding-top: 20px;">
				<h2>Toko Kopi Tuku</h2>
				<div class = "content-resto">
                    <h6>Jl. Cipete Raya No. 7, Fatmawati, Jakarta</h6>
                    <h6>021-71817627</h6>
					<p>Mengusung nama Tuku, toko kopi ini berarti "beli" dalam Bahasa Jawa. Meski baru satu tahun berdiri, toko kopi Tuku sudah cukup banyak dikenal warga Jakarta. Nampaknya omongan dari mulut ke mulut jadi salah satu faktor pemicunya. Tuku disebut-sebut punya racikan kopi enak dan ramah di kantong. Cocok juga bagi yang sekedar ingin membeli kopi tanpa berlama-lama. Bisa dikatakan semacam 'grab and go'. Tertarik, kami pun melangkahkan kaki ke wilayah Cipete tempat Tuku berada.</p>
				</div>
				<div class="container-btn">
					<div class="ml-auto">
						<button type="button" class="btn btn-warning" onclick="window.location.href={% url 'info:info' %}">Lihat</button>
					</div>
				</div>
			</div>
        </div>
        
        <div class = "resto clearfix">
			<div class = "img-resto left-section">
				<img src="{% static '/images/05.jpeg' %}" style="width: 300px; height: 200px;" alt="RESTORAN-DEPOK-01">
			</div>
			<div style="padding-top: 20px;">
				<h2>Walking Drums</h2>
				<div class = "content-resto">
                    <h6>Jl. Margonda Raya No. 426, Beji, Depok</h6>
                    <h6>021-74926162</h6>
					<p>Walking Drums memiliki beberapa area makan. Untuk area indoor ada 2 ruangan, satu berada dekat lapangan tenis dan satu lagi berada dekat parkiran yang diapit dengan 2 area outdoor. Bangunan utamanya adalah yang berada dekat dengan parkiran. Di area outdoor yang menghadap ke lapangan, ada kolam ikannya. Sepertinya jika cuaca tidak panas, seru juga makan di area outdoor ini. Keseluruhan area makan resto ini cozy dan homey untuk nongkrong ala cafe.</p>
				</div>
				<div class="container-btn">
					<div class="ml-auto">
						<button type="button" class="btn btn-warning" onclick="window.location.href={% url 'info:info' %}">Lihat</button>
					</div>
				</div>
			</div>
        </div>
        
               <div class = "resto clearfix">
			<div class = "img-resto left-section">
				<img src="{% static '/images/06.jpg' %}" style="width: 300px; height: 200px;" alt="RESTORAN-DEPOK-01">
			</div>
			<div style="padding-top: 20px;">
				<h2>Dejabrew Coffee and Eatery</h2>
				<div class = "content-resto">
                    <h6>Jl. Margonda Raya No. 267, Beji, Depok</h6>
                    <h6>021-75839475</h6>
					<p>Lokasinya di Jalan Margonda, di seberang Hotel Bumi Wiyata agak ke depan dikit. Dari luar udah keliatan plang nya. Tapi karena lokasinya di ruko, jadi sempit gitu. Tempat nya sendiri ada 2 lantai, yang atas untuk smoking area. Harga makanan dan minuman standar. Aku dan temen pesen iced chocotella latte, iced red velvet latte, french fries, dan chicken bowl. Minumannya pas banget di lidahku, enak gitu. Kalau makanan ya biasa aja sih. Di sini banyak colokan, dan enak buat jadi spot nugas dan berlama-lama karena wifi nya juga kenceng.</p>
				</div>
				<div class="container-btn">
					<div class="ml-auto">
						<button type="button" class="btn btn-warning" onclick="window.location.href={% url 'info:info' %}">Lihat</button>
					</div>
				</div>
			</div>
		</div> {% endcomment %}
</body>
</html>